### PR TITLE
Use UMD

### LINKED ISSUE #179: Don't check for `window`
See <https://github.com/Hardmath123/nearley/blob/master/lib/compile.js#L2>:
```js
if (typeof(window) === 'undefined') {
    var nearley = require('../lib/nearley.js');
} else {
    var nearley = window.nearley;
}
```
Some testing frameworks define `window`, so this check fails.

I think there are better conditions we could use here, e.g. the `typeof module !== 'undefined' && typeof module.exports !== 'undefined'` check seen at the bottom of the same file. :)

### PR DESCRIPTION
**Pull request by tjvr**
Fixes #179.

(I've disabled AMD for now, because we don't know of anyone who's using it; I don't want to claim to support stuff that we haven't tested!)

### CODE REVIEW

File: lib/nearley.js [hunk 1]
```diff
@@ -1,4 +1,13 @@
-(function () {
+(function(root, factory) {
+    // if (typeof define === 'function' && define.amd) {
```
Comment (vietlq) [inline lib/nearley.js]: I wouldn't recommend keeping comments like this.

Comment (tjvr) [inline lib/nearley.js]: If you want to go ahead and test nearley under AMD, go right ahead :)
